/// Per-request identifiers. Generated by `request_id` middleware and inserted
/// into the request extensions so handlers (and the error path) can echo them.
#[derive(Debug, Clone)]
pub struct RequestId {
    /// 16-char hex (`x-amz-request-id` response header).
    pub request_id: String,
    /// Opaque base64 token (`x-amz-id-2` response header).
    pub host_id: String,
}

/// Marker injected by the Sigv4 middleware after a request passes verification.
/// Handlers may extract it as `Extension<AuthenticatedIdentity>`.
#[derive(Debug, Clone)]
pub struct AuthenticatedIdentity {
    pub access_key_id: String,
}
